name: Mocha CI  | © 2024 by anh tú
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.4]  # Chọn phiên bản Node.js cần kiểm thử

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start server  # Khởi động server từ thư mục "server"
        run: |
          nohup node server/server.js &  # Chạy server.js ở chế độ nền
          sleep 5  # Đợi 5 giây để server khởi động hoàn toàn

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
